/**************
   WeatherDataID.h

   defines constants to use as Weather Data ID's by Expansion modules

   Weather Data IDs are based on these classes:

   the WeatherDataIDTag class describes the data variable with 6 bit fields.
   Not all combinations are valid

  The WeatherDataID union allows us to use a single DWORD (unsigned long-4 bytes) as an 
  alternitave representation of the bit field values

  This version of the File is designed to be used by the VantagePro DLL to 
  specify Current Data and High/Low data instead of data feom arhive records

struct WeatherDataIDTag    // the same size as a UINT
{
   unsigned int calculatedVar : 5; // calculated or direct value
   unsigned int displayUnits  : 5; // type of units
   unsigned int dataType      : 5; // Current, High/Low, Daily High/Low 
   unsigned int reserved      : 1; // space for future use

   unsigned int sensorType    : 8; // Or sensor Id 1 for calculated values
   unsigned int sensorId      : 8; // Or sensor Id 0 for calculated values

   bool IsCurrentVariable();  // is the ID valid for current data?
   bool IsHiLowVariable();    // is ID valid for Hi/Low data?

};

union WeatherDataID
{
   DWORD id;
   WeatherDataIDTag fields;
};

 **************/

#ifndef WDID_H
#define WDID_H

// Creates a Weather Data ID from the components
#define MAKE_WDID(CV, DU, DT, ST, SID)  ( ((CV) & 0x1F) | (((DU) & 0x1F)<<5) | (((DT) & 0x1F)<<10) | (((ST) & 0xFF)<<16) | (((SID) & 0xFF) <<24) )

// Weather Data ID field values

// Calculated Variable - 5 bits        // Input parameters
#define WDAT_CV_DIRECT_DATA      (0)   // NOT a calculated value, 
                                       // 0=SID   1=ST
#define WDAT_CV_DEWPOINT         (1)   // 0-Temp, 1-Humidity
#define WDAT_CV_WINDCHILL        (2)   // 0-Temp,             Implied: Wind Speed
#define WDAT_CV_HEAT             (3)   // 0-Temp, 1-Humidity
#define WDAT_CV_THWINDEX         (4)   // 0-Temp, 1-Humidity, Implied: Wind Speed
#define WDAT_CV_THSWINDEX        (5)   // 0-Temp, 1-Humidity, Implied: Speed, Solar, Time/Location
#define WDAT_CV_WETBULB          (6)   // 0-Temp, 1-Humidity
#define WDAT_CV_WINDRUN          (7)   //                     Implied: Speed, Arc Interval
#define WDAT_CV_DEGDAYS_INTEG    (8)   // 0-Temp, 1-Threshold Implied: Arc Interval
#define WDAT_CV_SOLAR_ENERGY     (9)   //                     Implied: Solar, Arc Interval
#define WDAT_CV_UV_DOSE          (10)  //                     Implied: UV, Arc Interval
#define WDAT_CV_AIR_DENSITY      (11)  // 0-Temp, 1-Humidity  Implied barometer
#define WDAT_CV_EMC              (12)  // 0-Temp, 1-Humidity
#define WDAT_CV_ET               (13)  // This is calculated on the Vantage, but does not have 
                                       // a particular sensor to file it under
#define WDAT_CV_DEGDAYS_HI_LOW   (14)  // 0-Temp, 1-Threshold Implied: Arc Interval

// Display Units - 5 bits - This is NOT an independant variable
#define WDAT_DU_TEMP_DEG         (0)   // Degrees of Temperature (F,C)
#define WDAT_DU_DEG_DAYS         (1)   // Degrees of Temp Accumulation (0F = 0C)
#define WD0      (2)   // Water Accumulation (Rain, ET) (in,mm)
#define WDAT_DU_WATER_ACCUM      (2)   // Water Accumulation (Rain, ET) (in,mm) -- another define
#define WDAT_DU_WATER_RATE       (3)   // Water Rate (in/hr, mm/hr)
#define WDAT_DU_SPEED            (4)   // Wind Speed (mph,kt,kph,m/s)
#define WDAT_DU_DIR_DEG          (5)   // Wind Direction in degrees 
#define WDAT_DU_DIR_SECTOR       (6)   // Wind Direction in sector code
#define WDAT_DU_PRESSURE         (7)   // Air Pressure (in Hg, mm Hg, mb)
#define WDAT_DU_TIME             (8)   // Time of Day (12hr, 24hr)
#define WDAT_DU_TIME_ACCUM       (9)   // Accumulated # minutes
#define WDAT_DU_SOLAR_RAD        (10)  // Solar Rad (W/m^2)
#define WDAT_DU_SOLAR_ENERGY     (11)  // Solar Energy (Ly)
#define WDAT_DU_UV_INDEX         (12)  // UV radiation (Index)
#define WDAT_DU_UV_DOSE          (13)  // UV Dose (MEDs)
#define WDAT_DU_PERCENT          (14)  // Percentage (i.e. Relative Hum) (%)
#define WDAT_DU_SOIL_MOISTURE    (15)  // Wetness of the Soil (cb)
#define WDAT_DU_LEAF_WET         (16)  // Wetness of Leaf surface (0-15)
#define WDAT_DU_SCALAR           (17)  // Dimensionless numbers (Reed Open, nSamples, etc)
#define WDAT_DU_DISTANCE         (18)  // Miles, Km, etc for Wind run
#define WDAT_DU_ELEVATION        (19)  // Feet or Meters. for Bar Calibration etc
#define WDAT_DU_AIR_DENSITY      (20)  // Air density units
#define WDAT_DU_BAR_TREND        (21)  // barometer trend (5-position)

// Data Type - 5 bits
#define WDAT_DT_CURRENT          (0)   // Current instantanious value
//#define WDAT_DT_ARC_ACCUM        (1)   // Accumulation over the archive interval
//#define WDAT_DT_HIGH             (2)   // High within an archive interval
//#define WDAT_DT_LOW              (3)   // Low within an archive interval
#define WDAT_DT_DAY_HIGH         (4)   // Daily High
//#define WDAT_DT_DAY_HIGH_TIME    (5)   // Time of Daily High
#define WDAT_DT_DAY_LOW          (6)   // Daily Low
//#define WDAT_DT_DAY_LOW_TIME     (7)   // Time of Daily Low
#define WDAT_DT_DAY_AVERAGE      (8)   // Daily Average
#define WDAT_DT_DAY_ACCUM        (9)   // Daily Accumulation
#define WDAT_DT_MONTH_HIGH       (10)  // Monthly High
//#define WDAT_DT_MONTH_HIGH_TIME  (11)  // Time of Monthly High
#define WDAT_DT_MONTH_LOW        (12)  // Monthly Low
//#define WDAT_DT_MONTH_LOW_TIME   (13)  // Time of Monthly Low
//#define WDAT_DT_MONTH_AVERAGE    (14)  // Monthly Average
//#define WDAT_DT_MONTH_AVG_HIGH   (15)  // Monthly Average of Daily Highs
//#define WDAT_DT_MONTH_AVG_LOW    (16)  // Monthly Average of Daily Lows
//#define WDAT_DT_MONTH_HIGH_AVG   (17)  // Monthly High of Daily Averages
//#define WDAT_DT_MONTH_LOW_AVG    (18)  // Monthly Low of Daily Averages
#define WDAT_DT_YEAR_HIGH        (19)  // Yearly high value
#define WDAT_DT_YEAR_LOW         (20)  // Yearly low value
#define WDAT_DT_STORM_ACCUM      (21)  // Month Accumulation
#define WDAT_DT_MONTH_ACCUM      (22)  // Month Accumulation
#define WDAT_DT_YEAR_ACCUM       (23)  // Year Accumulation
#define WDAT_DT_HOUR_HIGH        (24)  // Hourly High (Rain Rate Only)
// New for Loop 2
#define WDAT_DT_2MIN_AVG              (25)    // 2 Min Wind speed 
#define WDAT_DT_10MIN_HIGH            (26)    // 10 Min Wind gust
#define WDAT_DT_1HR_ACCUM             (27)    // Last hour rain
#define WDAT_DT_24HR_ACCUM            (28)    // Last 24 hour rain


// Sensor Type -- or Parameter 1 in calculated values - 8 bits
#define WDAT_ST_TEMPERATURE      (0)
#define WDAT_ST_HUMIDITY         (1)
#define WDAT_ST_SPEED            (2)
#define WDAT_ST_DIRECTION        (3)
#define WDAT_ST_BAROMETER        (4)
#define WDAT_ST_RAIN             (5)
#define WDAT_ST_RAIN_RATE        (6)
#define WDAT_ST_SOLAR            (7)
#define WDAT_ST_UV               (8)
#define WDAT_ST_SOIL             (9)
#define WDAT_ST_LEAF             (10)
#define WDAT_ST_TIME             (11)
#define WDAT_ST_NUMBER           (12)  // various dimensionless numbers


// Sensor ID (Temperature, Humidity, Soil, Leaf, Wind Speed?) - 8 bits
//  The meaning of these values depends on the Sensor Type
// Temp and Hum  values
#define WDAT_SID_TH_OUTSIDE      (0)
#define WDAT_SID_TH_INSIDE       (1)
#define WDAT_SID_TH_EX_2         (2)
#define WDAT_SID_TH_EX_3         (3)
#define WDAT_SID_TH_EX_4         (4)
#define WDAT_SID_TH_EX_5         (5)
#define WDAT_SID_TH_EX_6         (6)
#define WDAT_SID_TH_EX_7         (7)
#define WDAT_SID_TH_EX_8         (8)

// Temp, Soil (use the same id for temp and moisture)
#define WDAT_SID_T_SOIL_1        (9)
#define WDAT_SID_T_SOIL_2        (10)
#define WDAT_SID_T_SOIL_3        (11)
#define WDAT_SID_T_SOIL_4        (12)
//#define WDAT_SID_T_SOIL_5        (13)  // not used in DLL
//#define WDAT_SID_T_SOIL_6        (14)  // not used in DLL

// leaf wetness
#define WDAT_SID_T_LEAF_1        (15)
#define WDAT_SID_T_LEAF_2        (16)
//#define WDAT_SID_T_LEAF_3        (17)  // not used in DLL
//#define WDAT_SID_T_LEAF_4        (18)  // not used in DLL

// Wind Speed
#define WDAT_SID_WIND_SPEED      (0)
#define WDAT_SID_WIND_10_MIN     (1)

// Barometer
#define WDAT_SID_BAR_SEA_LEVEL   (0)
#define WDAT_SID_BAR_STATION     (1)
#define WDAT_SID_BAR_ALTIMETER   (2)    // Vue Altimeter

// Scalar Values use these IDs
//#define WDAT_SID_ARC_PERIOD      (0)  // not used in DLL
//#define WDAT_SID_TX_ID           (1)  // not used in DLL
//#define WDAT_SID_WIND_SAMPLES    (2)  // not used in DLL
//#define WDAT_SID_RECEPTION       (3)  // not used in DLL
//#define WDAT_SID_REED_OPEN       (4)  // not used in DLL
//#define WDAT_SID_REED_CLOSED     (5)  // not used in DLL
//#define WDAT_SID_REED_CYCLE      (6)  // not used in DLL
#define WDAT_SID_REC_TIME        (7)
//#define WDAT_SID_EXP_WIND_SAMPLES (8)  // not used in DLL
#define WDAT_SID_CON_BATT        (9)
#define WDAT_SID_TX_BATT         (10)
#define WDAT_SID_REP_BATT        (11)
#define WDAT_SID_FORECAST_CODE   (12)
#define WDAT_SID_FORECAST_ICON   (13)

// accumulated time values
#define WDAT_SID_DATA_SPAN       (0)  // not used in DLL
#define WDAT_SID_MIN_SUN         (1)  // not used in DLL
#define WDAT_SID_SUNRISE         (2)
#define WDAT_SID_SUNSET          (3)

//#define WDAT_SID_
//#define WDAT_SID_

// Anything Else
#define WDAT_SID_DEFAULT_SENSOR        (0)
#define WDAT_SID_EXTRA_RAD_SENSOR      (1)   // used for THSW Index calculation


// predefined sensor values

// outside temperature
#define CUR_OUT_TEMP_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_OUTSIDE)    
#define DAY_HI_OUT_TEMP_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_OUTSIDE)    
#define DAY_LOW_OUT_TEMP_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_OUTSIDE)    
#define MONTH_HI_OUT_TEMP_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_TH_OUTSIDE)    
#define MONTH_LOW_OUT_TEMP_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_TH_OUTSIDE)    
#define YEAR_HI_OUT_TEMP_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_TH_OUTSIDE)    
#define YEAR_LOW_OUT_TEMP_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_OUTSIDE)    

// inside temperature
#define CUR_IN_TEMP_WDID         MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_INSIDE)    
#define DAY_HI_IN_TEMP_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_INSIDE)    
#define DAY_LOW_IN_TEMP_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_INSIDE)    
#define MONTH_HI_IN_TEMP_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_TH_INSIDE)    
#define MONTH_LOW_IN_TEMP_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_TH_INSIDE)    
#define YEAR_HI_IN_TEMP_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_TH_INSIDE)    
#define YEAR_LOW_IN_TEMP_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_INSIDE)    

// Out humidity
#define CUR_OUT_HUM_WDID         MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_CURRENT,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_OUTSIDE)    
#define DAY_HI_OUT_HUM_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_HIGH,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_OUTSIDE)    
#define DAY_LOW_OUT_HUM_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_LOW,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_OUTSIDE)    
#define MONTH_HI_OUT_HUM_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_HIGH,WDAT_ST_HUMIDITY,    WDAT_SID_TH_OUTSIDE)    
#define MONTH_LOW_OUT_HUM_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_LOW, WDAT_ST_HUMIDITY,    WDAT_SID_TH_OUTSIDE)    
#define YEAR_HI_OUT_HUM_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_HIGH, WDAT_ST_HUMIDITY,    WDAT_SID_TH_OUTSIDE)    
#define YEAR_LOW_OUT_HUM_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_LOW,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_OUTSIDE)    

// In humidity
#define CUR_IN_HUM_WDID          MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_CURRENT,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_INSIDE)    
#define DAY_HI_IN_HUM_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_HIGH,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_INSIDE)    
#define DAY_LOW_IN_HUM_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_LOW,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_INSIDE)    
#define MONTH_HI_IN_HUM_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_HIGH,WDAT_ST_HUMIDITY,    WDAT_SID_TH_INSIDE)    
#define MONTH_LOW_IN_HUM_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_LOW, WDAT_ST_HUMIDITY,    WDAT_SID_TH_INSIDE)    
#define YEAR_HI_IN_HUM_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_HIGH, WDAT_ST_HUMIDITY,    WDAT_SID_TH_INSIDE)    
#define YEAR_LOW_IN_HUM_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_LOW,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_INSIDE)    

// Dew point
#define CUR_OUT_DEW_WDID         MAKE_WDID(WDAT_CV_DEWPOINT,    WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)
#define DAY_HI_OUT_DEW_WDID      MAKE_WDID(WDAT_CV_DEWPOINT,    WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)
#define DAY_LOW_OUT_DEW_WDID     MAKE_WDID(WDAT_CV_DEWPOINT,    WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)
#define MONTH_HI_OUT_DEW_WDID    MAKE_WDID(WDAT_CV_DEWPOINT,    WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)
#define MONTH_LOW_OUT_DEW_WDID   MAKE_WDID(WDAT_CV_DEWPOINT,    WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)
#define YEAR_HI_OUT_DEW_WDID     MAKE_WDID(WDAT_CV_DEWPOINT,    WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)
#define YEAR_LOW_OUT_DEW_WDID    MAKE_WDID(WDAT_CV_DEWPOINT,    WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)

// Wind Chill
#define CUR_WIND_CHILL_WDID      MAKE_WDID(WDAT_CV_WINDCHILL,   WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   0,                   WDAT_SID_TH_OUTSIDE)    
#define DAY_LOW_WIND_CHILL_WDID  MAKE_WDID(WDAT_CV_WINDCHILL,   WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   0,                   WDAT_SID_TH_OUTSIDE)    
#define MONTH_LOW_WIND_CHILL_WDID MAKE_WDID(WDAT_CV_WINDCHILL,  WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, 0,                   WDAT_SID_TH_OUTSIDE)    
#define YEAR_LOW_WIND_CHILL_WDID MAKE_WDID(WDAT_CV_WINDCHILL,   WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  0,                   WDAT_SID_TH_OUTSIDE)    

// Heat Index
#define CUR_OUT_HEAT_WDID        MAKE_WDID(WDAT_CV_HEAT,        WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)    
#define DAY_HI_OUT_HEAT_WDID     MAKE_WDID(WDAT_CV_HEAT,        WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)    
#define MONTH_HI_OUT_HEAT_WDID   MAKE_WDID(WDAT_CV_HEAT,        WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)    
#define YEAR_HI_OUT_HEAT_WDID    MAKE_WDID(WDAT_CV_HEAT,        WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)    

// THW Index - current data only
#define CUR_THW_INDEX_WDID       MAKE_WDID(WDAT_CV_THWINDEX,    WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)    

// THSW Index
#define CUR_THSW_INDEX_WDID      MAKE_WDID(WDAT_CV_THSWINDEX,   WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)    
#define DAY_HI_THSW_INDEX_WDID   MAKE_WDID(WDAT_CV_THSWINDEX,   WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)    
#define MONTH_HI_THSW_INDEX_WDID MAKE_WDID(WDAT_CV_THSWINDEX, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)    
#define YEAR_HI_THSW_INDEX_WDID  MAKE_WDID(WDAT_CV_THSWINDEX,  WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_SID_TH_OUTSIDE, WDAT_SID_TH_OUTSIDE)    

// inside Dew and Heat values - current data only
#define CUR_IN_DEW_WDID          MAKE_WDID(WDAT_CV_DEWPOINT,    WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_SID_TH_INSIDE,  WDAT_SID_TH_INSIDE)    
#define CUR_IN_HEAT_WDID         MAKE_WDID(WDAT_CV_HEAT,        WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_SID_TH_INSIDE,  WDAT_SID_TH_INSIDE)

// instantanious Wind Speed
#define CUR_SPEED_WDID           MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SPEED,    WDAT_DT_CURRENT,   WDAT_ST_SPEED,     WDAT_SID_WIND_SPEED)    
#define DAY_HI_SPEED_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SPEED,    WDAT_DT_DAY_HIGH,  WDAT_ST_SPEED,     WDAT_SID_WIND_SPEED)    
#define MONTH_HI_SPEED_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SPEED,    WDAT_DT_MONTH_HIGH,WDAT_ST_SPEED,     WDAT_SID_WIND_SPEED)    
#define YEAR_HI_SPEED_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SPEED,    WDAT_DT_YEAR_HIGH, WDAT_ST_SPEED,     WDAT_SID_WIND_SPEED)    

// wind values
#define CUR_AVG_SPEED_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SPEED,    WDAT_DT_CURRENT,   WDAT_ST_SPEED,     WDAT_SID_WIND_10_MIN)    

//wind Direction
#define CUR_WIND_DIR_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_DIR_DEG,  WDAT_DT_CURRENT,   WDAT_ST_DIRECTION, WDAT_SID_WIND_SPEED)    
#define CUR_WIND_DIR_SECTOR_WDID MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_DIR_SECTOR, WDAT_DT_CURRENT, WDAT_ST_DIRECTION, WDAT_SID_WIND_SPEED)    
//#define CUR_DIR_OF_GUST_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_DIR_SECTOR, WDAT_DT_HIGH,    WDAT_ST_DIRECTION, WDAT_SID_WIND_SPEED)    

//#define CUR_WIND_RUN_WDID        MAKE_WDID(WDAT_CV_WINDRUN,     WDAT_DU_DISTANCE,   WDAT_DT_ARC_ACCUM, WDAT_ST_SPEED,   WDAT_SID_WIND_SPEED)    

// barometer values
#define CUR_SEA_LEV_BAR_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PRESSURE, WDAT_DT_CURRENT,   WDAT_ST_BAROMETER, WDAT_SID_BAR_SEA_LEVEL)    
#define DAY_HI_SEA_LEV_BAR_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PRESSURE, WDAT_DT_DAY_HIGH,  WDAT_ST_BAROMETER, WDAT_SID_BAR_SEA_LEVEL)    
#define DAY_LOW_SEA_LEV_BAR_WDID MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PRESSURE, WDAT_DT_DAY_LOW,   WDAT_ST_BAROMETER, WDAT_SID_BAR_SEA_LEVEL)    
#define MONTH_HI_SEA_LEV_BAR_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA,WDAT_DU_PRESSURE,WDAT_DT_MONTH_HIGH,WDAT_ST_BAROMETER, WDAT_SID_BAR_SEA_LEVEL)    
#define MONTH_LOW_SEA_LEV_BAR_WDID MAKE_WDID(WDAT_CV_DIRECT_DATA,WDAT_DU_PRESSURE,WDAT_DT_MONTH_LOW, WDAT_ST_BAROMETER, WDAT_SID_BAR_SEA_LEVEL)    
#define YEAR_HI_SEA_LEV_BAR_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA,WDAT_DU_PRESSURE,WDAT_DT_YEAR_HIGH, WDAT_ST_BAROMETER, WDAT_SID_BAR_SEA_LEVEL)    
#define YEAR_LOW_SEA_LEV_BAR_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA,WDAT_DU_PRESSURE,WDAT_DT_YEAR_LOW,  WDAT_ST_BAROMETER, WDAT_SID_BAR_SEA_LEVEL)    

#define CUR_STATIOM_BAR_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PRESSURE, WDAT_DT_CURRENT,   WDAT_ST_BAROMETER, WDAT_SID_BAR_STATION)    
#define CUR_SEA_LEV_BAR_TREND_WDID MAKE_WDID(WDAT_CV_DIRECT_DATA,WDAT_DU_BAR_TREND,WDAT_DT_CURRENT,  WDAT_ST_BAROMETER, WDAT_SID_BAR_SEA_LEVEL)    

// rain totals
#define DAY_RAIN_WDID            MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_WATER_ACCUM, WDAT_DT_DAY_ACCUM,  WDAT_ST_RAIN,  WDAT_SID_DEFAULT_SENSOR)    
#define STORM_RAIN_WDID          MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_WATER_ACCUM, WDAT_DT_STORM_ACCUM,WDAT_ST_RAIN,  WDAT_SID_DEFAULT_SENSOR)    
#define MONTH_RAIN_WDID          MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_WATER_ACCUM, WDAT_DT_MONTH_ACCUM,WDAT_ST_RAIN,  WDAT_SID_DEFAULT_SENSOR)    
#define YEAR_RAIN_WDID           MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_WATER_ACCUM, WDAT_DT_YEAR_ACCUM, WDAT_ST_RAIN,  WDAT_SID_DEFAULT_SENSOR)    

// rain rate
#define CUR_RAIN_RATE_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_WATER_RATE,  WDAT_DT_CURRENT,    WDAT_ST_RAIN_RATE, WDAT_SID_DEFAULT_SENSOR)    
#define HOUR_HI_RATE_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_WATER_RATE,  WDAT_DT_HOUR_HIGH,  WDAT_ST_RAIN_RATE, WDAT_SID_DEFAULT_SENSOR)    
#define DAY_HI_RATE_WDID         MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_WATER_RATE,  WDAT_DT_DAY_HIGH,   WDAT_ST_RAIN_RATE, WDAT_SID_DEFAULT_SENSOR)    
#define MONTH_HI_RATE_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_WATER_RATE,  WDAT_DT_MONTH_HIGH, WDAT_ST_RAIN_RATE, WDAT_SID_DEFAULT_SENSOR)    
#define YEAR_HI_RATE_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_WATER_RATE,  WDAT_DT_YEAR_HIGH,  WDAT_ST_RAIN_RATE, WDAT_SID_DEFAULT_SENSOR)    

// ET
#define DAY_ET_WDID              MAKE_WDID(WDAT_CV_ET,       WDAT_DU_WATER_ACCUM, WDAT_DT_DAY_ACCUM,  WDAT_SID_DEFAULT_SENSOR, WDAT_SID_DEFAULT_SENSOR)    
#define MONTH_ET_WDID            MAKE_WDID(WDAT_CV_ET,       WDAT_DU_WATER_ACCUM, WDAT_DT_MONTH_ACCUM,WDAT_SID_DEFAULT_SENSOR, WDAT_SID_DEFAULT_SENSOR)    
#define YEAR_ET_WDID             MAKE_WDID(WDAT_CV_ET,       WDAT_DU_WATER_ACCUM, WDAT_DT_YEAR_ACCUM, WDAT_SID_DEFAULT_SENSOR, WDAT_SID_DEFAULT_SENSOR)    


// Solar / UV values
#define CUR_SOLAR_RAD_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOLAR_RAD, WDAT_DT_CURRENT,    WDAT_ST_SOLAR, WDAT_SID_DEFAULT_SENSOR)    
#define DAY_HI_SOLAR_RAD_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOLAR_RAD, WDAT_DT_DAY_HIGH,   WDAT_ST_SOLAR, WDAT_SID_DEFAULT_SENSOR)    
#define MONTH_HI_SOLAR_RAD_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOLAR_RAD, WDAT_DT_MONTH_HIGH, WDAT_ST_SOLAR, WDAT_SID_DEFAULT_SENSOR)    
#define YEAR_HI_SOLAR_RAD_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOLAR_RAD, WDAT_DT_YEAR_HIGH,  WDAT_ST_SOLAR, WDAT_SID_DEFAULT_SENSOR)    

//#define CUR_SOLAR_ENERGY_WDID    MAKE_WDID(WDAT_CV_SOLAR_ENERGY, WDAT_DU_SOLAR_ENERGY, WDAT_DT_ARC_ACCUM, WDAT_ST_SOLAR, WDAT_SID_DEFAULT_SENSOR)    
//#define CUR_EXTRA_SOLAR_RAD_WDID MAKE_WDID(WDAT_CV_DIRECT_DATA,  WDAT_DU_SOLAR_RAD,    WDAT_DT_CURRENT,   WDAT_ST_SOLAR, WDAT_SID_EXTRA_RAD_SENSOR)    
 
#define CUR_UV_WDID              MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_UV_INDEX, WDAT_DT_CURRENT,   WDAT_ST_UV,     WDAT_SID_DEFAULT_SENSOR)    
#define DAY_HI_UV_WDID           MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_UV_INDEX, WDAT_DT_DAY_HIGH,  WDAT_ST_UV,     WDAT_SID_DEFAULT_SENSOR)    
#define MONTH_HI_UV_WDID         MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_UV_INDEX, WDAT_DT_MONTH_HIGH,WDAT_ST_UV,     WDAT_SID_DEFAULT_SENSOR)    
#define YEAR_HI_UV_WDID          MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_UV_INDEX, WDAT_DT_YEAR_HIGH, WDAT_ST_UV,     WDAT_SID_DEFAULT_SENSOR)    

//#define CUR_UV_DOSE_WDID         MAKE_WDID(WDAT_CV_UV_DOSE,      WDAT_DU_UV_DOSE,   WDAT_DT_ARC_ACCUM, WDAT_ST_UV, WDAT_SID_DEFAULT_SENSOR)    

// Extra Temperatures 
#define CUR_TEMP_2_WDID          MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_2)    
#define DAY_HI_TEMP_2_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_2)    
#define DAY_LOW_TEMP_2_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_2)    
#define MONTH_HI_TEMP_2_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_2)    
#define MONTH_LOW_TEMP_2_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_2)    
#define YEAR_HI_TEMP_2_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_2)    
#define YEAR_LOW_TEMP_2_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_2)    

#define CUR_TEMP_3_WDID          MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_3)    
#define DAY_HI_TEMP_3_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_3)    
#define DAY_LOW_TEMP_3_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_3)    
#define MONTH_HI_TEMP_3_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_3)    
#define MONTH_LOW_TEMP_3_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_3)    
#define YEAR_HI_TEMP_3_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_3)    
#define YEAR_LOW_TEMP_3_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_3)    

#define CUR_TEMP_4_WDID          MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_4)    
#define DAY_HI_TEMP_4_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_4)    
#define DAY_LOW_TEMP_4_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_4)    
#define MONTH_HI_TEMP_4_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_4)    
#define MONTH_LOW_TEMP_4_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_4)    
#define YEAR_HI_TEMP_4_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_4)    
#define YEAR_LOW_TEMP_4_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_4)    

#define CUR_TEMP_5_WDID          MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_5)    
#define DAY_HI_TEMP_5_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_5)    
#define DAY_LOW_TEMP_5_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_5)    
#define MONTH_HI_TEMP_5_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_5)    
#define MONTH_LOW_TEMP_5_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_5)    
#define YEAR_HI_TEMP_5_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_5)    
#define YEAR_LOW_TEMP_5_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_5)    

#define CUR_TEMP_6_WDID          MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_6)    
#define DAY_HI_TEMP_6_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_6)    
#define DAY_LOW_TEMP_6_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_6)    
#define MONTH_HI_TEMP_6_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_6)    
#define MONTH_LOW_TEMP_6_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_6)    
#define YEAR_HI_TEMP_6_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_6)    
#define YEAR_LOW_TEMP_6_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_6)    

#define CUR_TEMP_7_WDID          MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_7)    
#define DAY_HI_TEMP_7_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_7)    
#define DAY_LOW_TEMP_7_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_7)    
#define MONTH_HI_TEMP_7_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_7)    
#define MONTH_LOW_TEMP_7_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_7)    
#define YEAR_HI_TEMP_7_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_7)    
#define YEAR_LOW_TEMP_7_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_7)    

#define CUR_TEMP_8_WDID          MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_8)    
#define DAY_HI_TEMP_8_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_8)    
#define DAY_LOW_TEMP_8_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_8)    
#define MONTH_HI_TEMP_8_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_8)    
#define MONTH_LOW_TEMP_8_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_8)    
#define YEAR_HI_TEMP_8_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_8)    
#define YEAR_LOW_TEMP_8_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_TH_EX_8)    

// Extra Humidities 
#define CUR_HUM_2_WDID           MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_CURRENT,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_2)    
#define DAY_HI_HUM_2_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_HIGH,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_2)    
#define DAY_LOW_HUM_2_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_LOW,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_2)    
#define MONTH_HI_HUM_2_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_HIGH,WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_2)    
#define MONTH_LOW_HUM_2_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_LOW, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_2)    
#define YEAR_HI_HUM_2_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_HIGH, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_2)    
#define YEAR_LOW_HUM_2_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_LOW,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_2)    

#define CUR_HUM_3_WDID           MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_CURRENT,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_3)    
#define DAY_HI_HUM_3_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_HIGH,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_3)    
#define DAY_LOW_HUM_3_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_LOW,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_3)    
#define MONTH_HI_HUM_3_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_HIGH,WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_3)    
#define MONTH_LOW_HUM_3_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_LOW, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_3)    
#define YEAR_HI_HUM_3_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_HIGH, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_3)    
#define YEAR_LOW_HUM_3_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_LOW,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_3)    

#define CUR_HUM_4_WDID           MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_CURRENT,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_4)    
#define DAY_HI_HUM_4_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_HIGH,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_4)    
#define DAY_LOW_HUM_4_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_LOW,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_4)    
#define MONTH_HI_HUM_4_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_HIGH,WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_4)    
#define MONTH_LOW_HUM_4_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_LOW, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_4)    
#define YEAR_HI_HUM_4_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_HIGH, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_4)    
#define YEAR_LOW_HUM_4_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_LOW,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_4)    

#define CUR_HUM_5_WDID           MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_CURRENT,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_5)    
#define DAY_HI_HUM_5_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_HIGH,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_5)    
#define DAY_LOW_HUM_5_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_LOW,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_5)    
#define MONTH_HI_HUM_5_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_HIGH,WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_5)    
#define MONTH_LOW_HUM_5_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_LOW, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_5)    
#define YEAR_HI_HUM_5_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_HIGH, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_5)    
#define YEAR_LOW_HUM_5_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_LOW,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_5)    

#define CUR_HUM_6_WDID           MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_CURRENT,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_6)    
#define DAY_HI_HUM_6_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_HIGH,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_6)    
#define DAY_LOW_HUM_6_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_LOW,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_6)    
#define MONTH_HI_HUM_6_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_HIGH,WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_6)    
#define MONTH_LOW_HUM_6_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_LOW, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_6)    
#define YEAR_HI_HUM_6_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_HIGH, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_6)    
#define YEAR_LOW_HUM_6_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_LOW,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_6)    

#define CUR_HUM_7_WDID           MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_CURRENT,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_7)    
#define DAY_HI_HUM_7_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_HIGH,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_7)    
#define DAY_LOW_HUM_7_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_LOW,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_7)    
#define MONTH_HI_HUM_7_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_HIGH,WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_7)    
#define MONTH_LOW_HUM_7_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_LOW, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_7)    
#define YEAR_HI_HUM_7_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_HIGH, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_7)    
#define YEAR_LOW_HUM_7_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_LOW,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_7)    

#define CUR_HUM_8_WDID           MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_CURRENT,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_8)    
#define DAY_HI_HUM_8_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_HIGH,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_8)    
#define DAY_LOW_HUM_8_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_DAY_LOW,   WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_8)    
#define MONTH_HI_HUM_8_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_HIGH,WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_8)    
#define MONTH_LOW_HUM_8_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_MONTH_LOW, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_8)    
#define YEAR_HI_HUM_8_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_HIGH, WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_8)    
#define YEAR_LOW_HUM_8_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PERCENT,  WDAT_DT_YEAR_LOW,  WDAT_ST_HUMIDITY,    WDAT_SID_TH_EX_8)    

//Soil Moisture
#define CUR_SOIL_M_1_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_CURRENT,   WDAT_ST_SOIL,   WDAT_SID_T_SOIL_1)
#define DAY_HI_SOIL_M_1_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_DAY_HIGH,  WDAT_ST_SOIL,   WDAT_SID_T_SOIL_1)
#define DAY_LOW_SOIL_M_1_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_DAY_LOW,   WDAT_ST_SOIL,   WDAT_SID_T_SOIL_1)
#define MONTH_HI_SOIL_M_1_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_MONTH_HIGH,WDAT_ST_SOIL,   WDAT_SID_T_SOIL_1)
#define MONTH_LOW_SOIL_M_1_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_MONTH_LOW, WDAT_ST_SOIL,   WDAT_SID_T_SOIL_1)
#define YEAR_HI_SOIL_M_1_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_YEAR_HIGH, WDAT_ST_SOIL,   WDAT_SID_T_SOIL_1)
#define YEAR_LOW_SOIL_M_1_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_YEAR_LOW,  WDAT_ST_SOIL,   WDAT_SID_T_SOIL_1)

#define CUR_SOIL_M_2_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_CURRENT,   WDAT_ST_SOIL,   WDAT_SID_T_SOIL_2)
#define DAY_HI_SOIL_M_2_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_DAY_HIGH,  WDAT_ST_SOIL,   WDAT_SID_T_SOIL_2)
#define DAY_LOW_SOIL_M_2_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_DAY_LOW,   WDAT_ST_SOIL,   WDAT_SID_T_SOIL_2)
#define MONTH_HI_SOIL_M_2_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_MONTH_HIGH,WDAT_ST_SOIL,   WDAT_SID_T_SOIL_2)
#define MONTH_LOW_SOIL_M_2_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_MONTH_LOW, WDAT_ST_SOIL,   WDAT_SID_T_SOIL_2)
#define YEAR_HI_SOIL_M_2_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_YEAR_HIGH, WDAT_ST_SOIL,   WDAT_SID_T_SOIL_2)
#define YEAR_LOW_SOIL_M_2_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_YEAR_LOW,  WDAT_ST_SOIL,   WDAT_SID_T_SOIL_2)

#define CUR_SOIL_M_3_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_CURRENT,   WDAT_ST_SOIL,   WDAT_SID_T_SOIL_3)
#define DAY_HI_SOIL_M_3_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_DAY_HIGH,  WDAT_ST_SOIL,   WDAT_SID_T_SOIL_3)
#define DAY_LOW_SOIL_M_3_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_DAY_LOW,   WDAT_ST_SOIL,   WDAT_SID_T_SOIL_3)
#define MONTH_HI_SOIL_M_3_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_MONTH_HIGH,WDAT_ST_SOIL,   WDAT_SID_T_SOIL_3)
#define MONTH_LOW_SOIL_M_3_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_MONTH_LOW, WDAT_ST_SOIL,   WDAT_SID_T_SOIL_3)
#define YEAR_HI_SOIL_M_3_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_YEAR_HIGH, WDAT_ST_SOIL,   WDAT_SID_T_SOIL_3)
#define YEAR_LOW_SOIL_M_3_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_YEAR_LOW,  WDAT_ST_SOIL,   WDAT_SID_T_SOIL_3)

#define CUR_SOIL_M_4_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_CURRENT,   WDAT_ST_SOIL,   WDAT_SID_T_SOIL_4)
#define DAY_HI_SOIL_M_4_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_DAY_HIGH,  WDAT_ST_SOIL,   WDAT_SID_T_SOIL_4)
#define DAY_LOW_SOIL_M_4_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_DAY_LOW,   WDAT_ST_SOIL,   WDAT_SID_T_SOIL_4)
#define MONTH_HI_SOIL_M_4_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_MONTH_HIGH,WDAT_ST_SOIL,   WDAT_SID_T_SOIL_4)
#define MONTH_LOW_SOIL_M_4_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_MONTH_LOW, WDAT_ST_SOIL,   WDAT_SID_T_SOIL_4)
#define YEAR_HI_SOIL_M_4_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_YEAR_HIGH, WDAT_ST_SOIL,   WDAT_SID_T_SOIL_4)
#define YEAR_LOW_SOIL_M_4_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SOIL_MOISTURE, WDAT_DT_YEAR_LOW,  WDAT_ST_SOIL,   WDAT_SID_T_SOIL_4)

// Soil Temperature
#define CUR_SOIL_T_1_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_1)
#define DAY_HI_SOIL_T_1_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_1)
#define DAY_LOW_SOIL_T_1_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_1)
#define MONTH_HI_SOIL_T_1_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_1)
#define MONTH_LOW_SOIL_T_1_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_1)
#define YEAR_HI_SOIL_T_1_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_1)
#define YEAR_LOW_SOIL_T_1_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_1)

#define CUR_SOIL_T_2_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_2)
#define DAY_HI_SOIL_T_2_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_2)
#define DAY_LOW_SOIL_T_2_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_2)
#define MONTH_HI_SOIL_T_2_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_2)
#define MONTH_LOW_SOIL_T_2_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_2)
#define YEAR_HI_SOIL_T_2_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_2)
#define YEAR_LOW_SOIL_T_2_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_2)

#define CUR_SOIL_T_3_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_3)
#define DAY_HI_SOIL_T_3_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_3)
#define DAY_LOW_SOIL_T_3_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_3)
#define MONTH_HI_SOIL_T_3_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_3)
#define MONTH_LOW_SOIL_T_3_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_3)
#define YEAR_HI_SOIL_T_3_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_3)
#define YEAR_LOW_SOIL_T_3_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_3)

#define CUR_SOIL_T_4_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_4)
#define DAY_HI_SOIL_T_4_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_4)
#define DAY_LOW_SOIL_T_4_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_4)
#define MONTH_HI_SOIL_T_4_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_4)
#define MONTH_LOW_SOIL_T_4_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_4)
#define YEAR_HI_SOIL_T_4_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_4)
#define YEAR_LOW_SOIL_T_4_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_T_SOIL_4)

// Leaf Wetness
#define CUR_LEAF_W_1_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_CURRENT,   WDAT_ST_LEAF,        WDAT_SID_T_LEAF_1)
#define DAY_HI_LEAF_W_1_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_DAY_HIGH,  WDAT_ST_LEAF,        WDAT_SID_T_LEAF_1)
#define DAY_LOW_LEAF_W_1_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_DAY_LOW,   WDAT_ST_LEAF,        WDAT_SID_T_LEAF_1)
#define MONTH_HI_LEAF_W_1_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_MONTH_HIGH,WDAT_ST_LEAF,        WDAT_SID_T_LEAF_1)
#define MONTH_LOW_LEAF_W_1_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_MONTH_LOW, WDAT_ST_LEAF,        WDAT_SID_T_LEAF_1)
#define YEAR_HI_LEAF_W_1_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_YEAR_HIGH, WDAT_ST_LEAF,        WDAT_SID_T_LEAF_1)
#define YEAR_LOW_LEAF_W_1_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_YEAR_LOW,  WDAT_ST_LEAF,        WDAT_SID_T_LEAF_1)

#define CUR_LEAF_W_2_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_CURRENT,   WDAT_ST_LEAF,        WDAT_SID_T_LEAF_2)
#define DAY_HI_LEAF_W_2_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_DAY_HIGH,  WDAT_ST_LEAF,        WDAT_SID_T_LEAF_2)
#define DAY_LOW_LEAF_W_2_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_DAY_LOW,   WDAT_ST_LEAF,        WDAT_SID_T_LEAF_2)
#define MONTH_HI_LEAF_W_2_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_MONTH_HIGH,WDAT_ST_LEAF,        WDAT_SID_T_LEAF_2)
#define MONTH_LOW_LEAF_W_2_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_MONTH_LOW, WDAT_ST_LEAF,        WDAT_SID_T_LEAF_2)
#define YEAR_HI_LEAF_W_2_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_YEAR_HIGH, WDAT_ST_LEAF,        WDAT_SID_T_LEAF_2)
#define YEAR_LOW_LEAF_W_2_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_LEAF_WET, WDAT_DT_YEAR_LOW,  WDAT_ST_LEAF,        WDAT_SID_T_LEAF_2)

// Leaf Temperature
#define CUR_LEAF_T_1_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_1)
#define DAY_HI_LEAF_T_1_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_1)
#define DAY_LOW_LEAF_T_1_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_1)
#define MONTH_HI_LEAF_T_1_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_1)
#define MONTH_LOW_LEAF_T_1_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_1)
#define YEAR_HI_LEAF_T_1_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_1)
#define YEAR_LOW_LEAF_T_1_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_1)

#define CUR_LEAF_T_2_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_CURRENT,   WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_2)
#define DAY_HI_LEAF_T_2_WDID     MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_HIGH,  WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_2)
#define DAY_LOW_LEAF_T_2_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_DAY_LOW,   WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_2)
#define MONTH_HI_LEAF_T_2_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_HIGH,WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_2)
#define MONTH_LOW_LEAF_T_2_WDID  MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_MONTH_LOW, WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_2)
#define YEAR_HI_LEAF_T_2_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_HIGH, WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_2)
#define YEAR_LOW_LEAF_T_2_WDID   MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TEMP_DEG, WDAT_DT_YEAR_LOW,  WDAT_ST_TEMPERATURE, WDAT_SID_T_LEAF_2)

// Other values
#define CONSOLE_BATT_WDID        MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SCALAR,   WDAT_DT_CURRENT,   WDAT_ST_NUMBER,      WDAT_SID_CON_BATT)
#define TX_BATT_WDID             MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SCALAR,   WDAT_DT_CURRENT,   WDAT_ST_NUMBER,      WDAT_SID_TX_BATT)
#define REPEATER_BATT_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SCALAR,   WDAT_DT_CURRENT,   WDAT_ST_NUMBER,      WDAT_SID_REP_BATT)
#define FORECAST_WDID            MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SCALAR,   WDAT_DT_CURRENT,   WDAT_ST_NUMBER,      WDAT_SID_FORECAST_CODE)
#define FORECAST_ICON_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SCALAR,   WDAT_DT_CURRENT,   WDAT_ST_NUMBER,      WDAT_SID_FORECAST_ICON)
#define SUNRISE_WDID             MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TIME,     WDAT_DT_CURRENT,   WDAT_ST_TIME,        WDAT_SID_SUNRISE)
#define SUNSET_WDID              MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_TIME,     WDAT_DT_CURRENT,   WDAT_ST_TIME,        WDAT_SID_SUNSET)

// LOOP2 data
#define WIND_2MIN_AVG_WDID         MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SPEED,    WDAT_DT_CURRENT,    WDAT_ST_SPEED,       WDAT_DT_2MIN_AVG)    
#define WIND_GUST_10MIN_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_SPEED,    WDAT_DT_CURRENT,   WDAT_ST_SPEED,     WDAT_DT_10MIN_HIGH)    
#define LAST_HOUR_RAIN_WDID      MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_WATER_ACCUM, WDAT_DT_1HR_ACCUM,   WDAT_ST_RAIN,        WDAT_SID_DEFAULT_SENSOR)    
#define LAST_24HOUR_RAIN_WDID    MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_WATER_ACCUM, WDAT_DT_24HR_ACCUM,  WDAT_ST_RAIN,        WDAT_SID_DEFAULT_SENSOR)    
#define BAR_ALTIMETER_WDID       MAKE_WDID(WDAT_CV_DIRECT_DATA, WDAT_DU_PRESSURE,    WDAT_DT_CURRENT,  WDAT_ST_BAROMETER,   WDAT_SID_BAR_ALTIMETER)    

#endif
